### GET all contacts
GET http://localhost:8080/contacts

### GET contact by ID
GET http://localhost:8080/contacts/69fce6327d67700d3380d8b3

### CREATE contact
POST http://localhost:8080/contacts
Content-Type: application/json

{
  "firstName": "Laura",
  "lastName": "Hernandez",
  "email": "laura@example.com",
  "favoriteColor": "Pink",
  "birthday": "2001-04-12"
}
### UPDATE contact
PUT http://localhost:8080/contacts/6a07ad2f4da9d81056a1d881
Content-Type: application/json
### DELETE contact
DELETE http://localhost:8080/contacts/6a07ae717661a6670656c75c

{
  "firstName": "Laura Updated",
  "lastName": "Hernandez",
  "email": "lauraupdated@example.com",
  "favoriteColor": "Black",
  "birthday": "2001-04-12"
}